### ISSUE TITLE
Consider offering a `--test` script

### ISSUE THREAD

**Issue by jbalsas** [bryceosterhaus/liferay-npm-scripts#4]
We've basically started to converge around `jest` for testing purposes. As simple as it usually is to configure, it would be good to also offer this by default. Particularly interesting might be some default configuration like:

```json
"jest": {
	"globals": {
		...
	},
	"setupFiles": [
		...
	],
        "setupTestFrameworkScriptFile": "<rootDir>/test/js/setup.js",
	"testMatch": [
		"**/test/**/*.js"
	],
	...
	"testResultsProcessor": "./node_modules/liferay-jest-junit-reporter",
	"testURL": "http://localhost",
	"transformIgnorePatterns": [
		"<rootDir>.*(node_modules)(?!.*metal.*).*$"
	]
}
```

We also have some divergence between `jest` and `jest --coverage` so it would be good to make an informed decision about defaults and options here.

**Comment by bryceosterhaus** [comment]
I initially went down this road and tried to come up with some sort of default config but had a hard time reconciling all of the different Jest setups we already use.

I am gonna spend some more time looking into it today and see if its viable to add for the first 1.0.0 release or if we should wait.

**Comment by jbalsas** [comment]
Sounds good, Bryce! I think here the question might be not so much on how to reconcile the different setups as to which should be the default one. Some of the existing ones might be flat out wrong (although they work), but we could benefit from better defaults and guidelines. 

For one, proper integration with CI requires that we use `"testResultsProcessor": "./node_modules/liferay-jest-junit-reporter"` yet some modules don't know about this so those tests never run properly...

**Comment by bryceosterhaus** [comment]
Oh interesting. I wasn't aware of that requirement by CI. Definitely makes sense to try and come up with a default config then.

**Comment by bryceosterhaus** [comment]
Added it https://github.com/bryceosterhaus/liferay-npm-scripts/commit/142c1847ef6269b6bcb0649973ec66ed09e7149b

Still might be missing a few things from the default config, ill test it on a variety of modules and see.
